//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MissionPlanner.HUD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("udpsrc port=%d ! application/x-rtp,encoding-name=H264,payload=96 ! rtph264depay !" +
            " avdec_h264 ! videoconvert ! autovideosink")]
        public string PipelineString {
            get {
                return ((string)(this["PipelineString"]));
            }
            set {
                this["PipelineString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("udpsrc port=%d  buffer-size=60000 ! application/x-rtp,encoding-name=H264,payload=" +
            "96 ! rtph264depay ! h264parse ! tee name=record ! queue ! avdec_h264 ! video/x-r" +
            "aw, format=I420 ! d3dvideosink sync=false record. ! queue ! mp4mux ! filesink lo" +
            "cation = %s")]
        public string PipelineStringRecord {
            get {
                return ((string)(this["PipelineStringRecord"]));
            }
            set {
                this["PipelineStringRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9000")]
        public int UDPPort {
            get {
                return ((int)(this["UDPPort"]));
            }
            set {
                this["UDPPort"] = value;
            }
        }
    }
}
